<script lang="ts" module>
	import {
		Activity,
		Award,
		Banknote,
		Bell,
		BellRing,
		Bitcoin,
		BookOpen,
		Building2,
		Calendar,
		Car,
		ChartLine,
		ChartPie,
		Check,
		ChevronDown,
		ChevronLeft,
		ChevronRight,
		Circle,
		CircleDollarSign,
		Clock,
		Coffee,
		Coins,
		CreditCard,
		Download,
		Edit,
		Ellipsis,
		Eye,
		EyeOff,
		Funnel,
		Gift,
		GraduationCap,
		HeartPulse,
		Home,
		Info,
		KeyRound,
		Landmark,
		Laptop,
		LayoutDashboard,
		Lightbulb,
		Lock,
		LogOut,
		MapPin,
		Menu,
		Moon,
		Pencil,
		PiggyBank,
		Plane,
		Plus,
		ReceiptText,
		RefreshCw,
		Repeat,
		Search,
		Settings,
		Shield,
		ShieldCheck,
		ShoppingBag,
		SlidersHorizontal,
		Smartphone,
		Sparkles,
		Star,
		Sun,
		Tag,
		Target,
		Trash2,
		TrendingDown,
		TrendingUp,
		User,
		Users,
		Utensils,
		Wallet,
		X,
		Zap,
		ArrowUp,
		ArrowDown,
		ArrowUpRight,
		ArrowDownRight,
		ArrowRight,
		type Icon as IconType
	} from '@lucide/svelte';

	export const iconMap: Record<string, typeof IconType> = {
		activity: Activity,
		award: Award,
		banknote: Banknote,
		bell: Bell,
		'bell-ring': BellRing,
		bitcoin: Bitcoin,
		'book-open': BookOpen,
		building: Building2,
		calendar: Calendar,
		car: Car,
		'line-chart': ChartLine,
		'pie-chart': ChartPie,
		check: Check,
		'chevron-down': ChevronDown,
		'chevron-left': ChevronLeft,
		'chevron-right': ChevronRight,
		circle: Circle,
		'circle-dollar': CircleDollarSign,
		clock: Clock,
		coffee: Coffee,
		coins: Coins,
		'credit-card': CreditCard,
		download: Download,
		edit: Edit,
		ellipsis: Ellipsis,
		eye: Eye,
		'eye-off': EyeOff,
		funnel: Funnel,
		gift: Gift,
		graduation: GraduationCap,
		'heart-pulse': HeartPulse,
		home: Home,
		info: Info,
		key: KeyRound,
		landmark: Landmark,
		laptop: Laptop,
		dashboard: LayoutDashboard,
		lightbulb: Lightbulb,
		lock: Lock,
		'log-out': LogOut,
		'map-pin': MapPin,
		menu: Menu,
		moon: Moon,
		pencil: Pencil,
		'piggy-bank': PiggyBank,
		plane: Plane,
		plus: Plus,
		receipt: ReceiptText,
		refresh: RefreshCw,
		repeat: Repeat,
		search: Search,
		settings: Settings,
		shield: Shield,
		'shield-check': ShieldCheck,
		'shopping-bag': ShoppingBag,
		sliders: SlidersHorizontal,
		smartphone: Smartphone,
		sparkles: Sparkles,
		star: Star,
		sun: Sun,
		tag: Tag,
		target: Target,
		trash: Trash2,
		'trending-down': TrendingDown,
		'trending-up': TrendingUp,
		user: User,
		users: Users,
		utensils: Utensils,
		wallet: Wallet,
		x: X,
		zap: Zap,
		'arrow-up': ArrowUp,
		'arrow-down': ArrowDown,
		'arrow-up-right': ArrowUpRight,
		'arrow-down-right': ArrowDownRight,
		'arrow-right': ArrowRight
	};
</script>

<script lang="ts">
	interface Props {
		name: string;
		size?: number;
		strokeWidth?: number;
		class?: string;
	}

	let { name, size = 20, strokeWidth = 2, class: klass = '' }: Props = $props();

	const Cmp = $derived(iconMap[name] ?? Circle);
</script>

<Cmp {size} {strokeWidth} class={klass} aria-hidden="true" />
